name = "media-verification-platform-v2"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "media-verification-platform-v2-db"
database_id = "d948e5d6-adea-46a3-8134-adaaebf062ea"


