name = "media-verification-platform-v2"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "media-verification-platform-v2-db"
database_id = "b1978423-a4a8-434f-af99-715fb4edd86c"


